# Stack name: curl-performance-common

AWSTemplateFormatVersion: 2010-09-09

Description: Common resources for monitoring services

Parameters:
  BucketName:
    Description: Name of the artifacts bucket to be created
    Type: String
  NotificationEndpoint:
    Description: Email address
    Type: String

Conditions:
  NotificationEnabled: !Not [!Equals [!Ref NotificationEndpoint, '']]

Resources:
  AlertTopic:
    Type: AWS::SNS::Topic
    Condition: NotificationEnabled
    Properties:
      Subscription:
        - Endpoint: !Ref NotificationEndpoint
          Protocol: email
      TopicName: CurlPerformanceTestAlertTopic

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 365
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  AlertTopicArn:
    Condition: NotificationEnabled
    Description: Curl Performance Test Alert SNS Topic ARN
    Value: !Ref AlertTopic
  ArtifactsBucketName:
    Description: The name of the S3 bucket that holds the lambda zip files.
    Value: !Ref ArtifactsBucket
