name: delete-curl-performance-test

on:
  workflow_dispatch:
    inputs:
      accountid:
        description: 'ID of the AWS account to deploy into'
        required: true
      region:
        description: 'Target deployment region'
        required: true
        default: 'ap-southeast-2'

defaults:
  run:
    shell: bash

jobs:
  echo-parameters:
    name: parameters
    runs-on: ubuntu-20.04
    continue-on-error: false
    steps:
      - name: accountid ${{ github.event.inputs.accountid }}
        run: echo
      - name: region ${{ github.event.inputs.region }}
        run: echo

  delete-curl-performance-test:
    name: Delete curl-performance-test stack
    runs-on: [self-hosted, linux, python3]
    env:
      AWS_REGION: ap-southeast-2
      AWS_ROLE_SESSION_NAME: GitHubActions
      accountid: ${{ github.event.inputs.accountid }}
      region: ${{ github.event.inputs.region }}
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.region }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          role-to-assume: arn:aws:iam::${{ env.accountid }}:role/k-ci-deploy

      - name: Delete CloudWatch Dashboard CurlPerformance
        run: aws cloudwatch delete-dashboards --dashboard-names CurlPerformance
      - name: Delete curl-performance-test-main stack
        run: aws cloudformation delete-stack --stack-name curl-performance-test-main

      - name: Wait until curl-performance-test-main stack delete complete
        run: aws cloudformation wait stack-delete-complete --stack-name curl-performance-test-main
